<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pony</string>
	</array>
	<key>name</key>
	<string>Pony</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>';
			end = '</string>
			<key>name</key>
			<string>string.quoted.single.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pony</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(actor|addressof|and|as|be|break|class|compile_error|compile_intrinsic)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(consume|continue|delegate|digestof|do|else|elseif|embed|end|error)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|fun|if|ifdef|in|interface|is|isnt|lambda|let|match|new|not|object)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(or|primitive|recover|repeat|return|struct|then|trait|try|type|until)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(use|var|where|while|with|xor)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(iso|val|tag|trn|box|ref)\b</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|this)\b</string>
			<key>name</key>
			<string>constant.language.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0b[0-1_]*)|(0x[0-9a-fA-F_]*)|([0-9][0-9_]*(\.[0-9][0-9_]*)?((e|E)(\+|-)?[0-9_]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|be|fun)\s+(iso|trn|ref|val|box|tag)?\b\s*([_a-z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>keyword.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|be|fun)\s+(iso|trn|ref|val|box|tag)?\b\s*([_a-z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|be|fun)\s+(iso|trn|ref|val|box|tag)?\b\s*([_a-z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>entity.name.function.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|interface|trait|primitive|struct|class|actor)\s+(iso|trn|ref|val|box|tag)?@?\s*([_A-Z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>keyword.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|interface|trait|primitive|struct|class|actor)\s+(iso|trn|ref|val|box|tag)?@?\s*([_A-Z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>keyword.other.capability.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|interface|trait|primitive|struct|class|actor)\s+(iso|trn|ref|val|box|tag)?@?\s*([_A-Z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>entity.name.type.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([_a-z][_a-zA-Z0-9]*)\b(\(|\[)</string>
			<key>name</key>
			<string>support.function.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\s*([_a-z][_a-zA-Z0-9]*)\b[^\(\[]</string>
			<key>name</key>
			<string>variable.parameter.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\s*([_a-zA-z][_a-zA-Z0-9]*)\s*(\(|\[)</string>
			<key>name</key>
			<string>support.function.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_*[A-Z][_a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>entity.name.type.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(compile_intrinsic|compile_error)\b</string>
			<key>name</key>
			<string>keyword.other.intrinsic.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(use)\b</string>
			<key>name</key>
			<string>keyword.other.import.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|let|embed|delegate)\b</string>
			<key>name</key>
			<string>keyword.other.declaration.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(iso|trn|ref|val|box|tag)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|continue|return|error)\b</string>
			<key>name</key>
			<string>keyword.control.jump.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|ifdef|then|elseif|else|end|match|where|try|with|as|recover|consume|object|digestof)\b</string>
			<key>name</key>
			<string>keyword.control.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(while|do|repeat|until|for|in)\b</string>
			<key>name</key>
			<string>keyword.control.loop.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\?|[-=]&gt;)</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|/(?![/*])|%|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is|isnt|not|and|or|xor)\b</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\||\&amp;|\,|\^)</string>
			<key>name</key>
			<string></string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pony</string>
	<key>uuid</key>
	<string>4B5BB96E-8565-433A-8CE2-CB982755F917</string>
</dict>
</plist>
