<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>Pony</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>';
			end = '</string>
			<key>name</key>
			<string>string.quoted.single.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.double.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abefnprtv'"?]|[0-3]\d{0,2}|[4-7]\d?|x[a-fA-F0-9]{0,2}|u[a-fA-F0-9]{0,4}|U[a-fA-F0-9]{0,8})</string>
					<key>name</key>
					<string>constant.character.escape.c</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.pony</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.pony</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this)\b</string>
			<key>name</key>
			<string>constant.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0b[0-1_]*)|(0x[0-9a-fA-F_]*)|([0-9][0-9_]*(\.[0-9][0-9_]*)?((e|E)(\+|-)?[0-9_]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|be|fun)\b</string>
			<key>name</key>
			<string>keyword.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|interface|trait|primitive|struct|class|actor)\b</string>
			<key>name</key>
			<string>keyword.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(iso|trn|ref|val|box|tag)\b</string>
			<key>name</key>
			<string>keyword.other.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([_a-z][_a-zA-Z0-9]*)\b(\(|\[)</string>
			<key>name</key>
			<string>support.function.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\s*([_a-z][_a-zA-Z0-9]*)\b[^\(\[]</string>
			<key>name</key>
			<string>variable.parameter.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\s*([_a-zA-z][_a-zA-Z0-9]*)\s*(\(|\[)</string>
			<key>name</key>
			<string>support.function.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_*[A-Z][_a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>entity.name.type.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(compile_intrinsic|compile_error)\b</string>
			<key>name</key>
			<string>keyword.other.intrinsic.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(use)\b</string>
			<key>name</key>
			<string>keyword.other.import.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|let|embed|delegate)\b</string>
			<key>name</key>
			<string>keyword.other.declaration.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(iso|trn|ref|val|box|tag)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|continue|return|error)\b</string>
			<key>name</key>
			<string>keyword.control.jump.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|ifdef|then|elseif|else|end|match|where|try|with|as|recover|consume|object|digestof)\b</string>
			<key>name</key>
			<string>keyword.control.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(while|do|repeat|until|for|in)\b</string>
			<key>name</key>
			<string>keyword.control.loop.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\?|[-=]&gt;)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|/(?![/*])|%|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is|isnt|not|and|or|xor)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\||\&amp;|\,|\^)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pony</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>4B5BB96E-8565-433A-8CE2-CB982755F917</string>
</dict>
</plist>
